#!/bin/sh

userresources=$HOME/.config/xres/current
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

init_dwm () {
    /home/tarun/sc/wn 900 &
    lxsession &
    dwmblocks &
    xautolock -time 30 -locker slock -notify 5 -notifier "notify-send 'Screen will lock in 5 s'" -corners 0-00 &
    clipmenud &
    exec dwm > /home/tarun/.local/share/.dwm.log
}

init_normie () {
    nm-applet &
    voltctl &
    cbatticon &
    exec openbox-session
}

xset b off &
xset r rate 300 50
xsetroot -cursor_name left_ptr &
setxkbmap us &
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/pipewire-media-session &
picom -b &
/home/tarun/.fehbg &

session=${1:-dwm}

case $session in
    dwm               ) init_dwm;;
    normie            ) init_normie;;
    *                 ) exec $1;;
esac
# exec openbox-session

