#!/bin/sh

case $BUTTON in
	4) xbacklight -inc 10 ;;
	5) xbacklight -dec 10 ;;
esac

for battery in /sys/class/power_supply/BAT?*; do
	capacity=$(cat "$battery/capacity")
    batstatus=$(cat /sys/class/power_supply/BAT0/status)
    if [[ $batstatus = "Discharging" ]]; then
        chargingicon="ﮤ"
    else
        chargingicon="ﮣ"
    fi	
    printf "%s   %d%%\n" "$chargingicon" "$capacity";
done && exit 0
