#!/bin/sh

case $BUTTON in
    1) kill -37 $(pidof dwmblocks) ;;
    6) alacritty -e nmtui ;;
esac

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
	down) wifiicon="睊" ;;
	up) wifiicon="$(awk '/^\s*w/ { print "直", int($3 * 100 / 70) "%" }' /proc/net/wireless)" ;;
esac

printf "%s\n" "$wifiicon"
